#
# SPDX-License-Identifier: BUSL-1.1
#

repository:
  name: mobile-sdk
  description: Evernym's SDK for building mobile identity agents. This is a read-only mirror. For support, please contact Evernym.
  homepage: http://evernym.com/products/#mobilesdk
  default_branch: master
  has_downloads: true
  has_issues: false
  has_projects: false
  has_wiki: false
  archived: false
  private: false
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
