# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'CMeSdkSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ConnectMe
  pod 'vcx', :path => '/Users/pedja/work/evernym/mobileSDK/vcx.podspec'

  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'

  target 'CMeSdkSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CMeSdkSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
