# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:evernym/mobile-sdk.git'

target 'CMeSdkObjc' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for CMeSdkObjc
  pod 'vcx', :path => '../../../vcx.podspec'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'QRCodeReaderViewController'

  target 'CMeSdkObjcTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CMeSdkObjcUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
